# Generated by Django 4.2.4 on 2024-01-04 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmodel',
            old_name='completed',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='empmodel',
            name='Days',
        ),
        migrations.AddField(
            model_name='empmodel',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
