# Generated by Django 4.2.4 on 2024-01-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
